### ISSUE TITLE
Run model on 4090

### ISSUE THREAD

**Issue by minhup** [jzr99/Geo4D#5]
Hi authors,

Thank you for sharing your great work. I have tried to run demo video on Nvidia 4090 (24GB of memory) using "bash ./scripts/infer_geo4d.sh ./data/demo/drift-turn.mp4 0" but got out of memory issue. The paper specifies the GPUs using were H100 but I wonder there away to run the model (inference only) on 4090? I have tried to reduce the video_length in bash file but it didn't work. Seems like 16 is hard coded in side the model.

Thanks

**Comment by jzr99** [comment]
Hi, Thanks for your interest.

I reduce the GPU memory usage, now it can feed into a single RTX4090 GPU. Try it again!

Best,
Zeren

**Comment by minhup** [comment]
It works now. Thank you for your prompt support.
